### ISSUE TITLE
What does users.sql do?

### ISSUE THREAD

**Issue by Modjular** [turbio/infotech-final#7]

**Comment by turbio** [comment]
the /tables/ directory holds the schema for all the different tables. This way you easily use a different database and quickly add all the tables by importing their .sql file. it also makes sure there won't be any issues with the database or table not being setup correctly. I'm running my own lamp stack on my client and i want to avoid there being any problems with differences between our databases. That's also why I added /config/database.php to .gitignore, so that our different configurations won't conflict with each other.

**Comment by Modjular** [comment]
What is the purpose of gitignore?

**Comment by turbio** [comment]
the .gitignore file tells git to ignore all the file listed inside it. i added database.php because the database configuration is host specific. so basically my database.php will be different from your database.php because i'm connecting to a different sql database.
